In [1]:
import numpy as np

In [2]:
# 创建3 x 3的多维数组（矩阵）
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 访问元素

In [3]:
# 访问元素
a[0,0]

1

In [4]:
a[1,1]

5

In [5]:
# 取出第1列
a[:,0]

array([1, 4, 7])

In [6]:
# 取出第1行
a[0,:]

array([1, 2, 3])

In [7]:
# 取出第2、3列
a[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [8]:
# 取出第2、3行
a[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [9]:
b = a[0]
b

array([1, 2, 3])

In [10]:
# 使用数组访问元素
c = [2, 0]
b[c]

array([3, 1])

In [11]:
b[[0,1]]

array([1, 2])

# 基本属性

In [12]:
# a的维度
a.ndim

2

In [13]:
# a的形状
a.shape

(3, 3)

In [14]:
# a的元素数
a.size

9

# 数组合并

- hstack: 水平合并
- vstack: 垂直合并

In [15]:
a = [[1], [2], [3]]
b = [[4], [5], [6]]
np.hstack([a, b])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
a = [1, 2, 3]
b = [4, 5, 6]
np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

# 转置矩阵

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# 广播

NumPy数组之间做逐元素的计算，要求数组的形状必须一致。在不一致的时候，会尝试调整为一致。

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# 首先把10调整成3x3的全元素为10的矩阵，然后逐元素相加
a + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [21]:
# 首先把3调整成3x3的全元素为3的矩阵，然后逐元素相乘
a * 3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [22]:
# 分别把a的每一列乘以2、3、4
a * [2, 3, 4]

array([[ 2,  6, 12],
       [ 8, 15, 24],
       [14, 24, 36]])

In [23]:
# 分别把a的每一行乘以2、3、4
a * np.vstack([2, 3, 4])

array([[ 2,  4,  6],
       [12, 15, 18],
       [28, 32, 36]])